packaging_format = 2

id = "z-push"
name = "Z-Push"
description.en = "ActiveSync frontend that helps you synchronize emails, calendar and contacts"
description.fr = "Frontend ActiveSync qui permet de synchroniser emails, calendrier et contacts"

version = "2.7.5~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "http://z-push.org"
admindoc = "https://github.com/Z-Hub/Z-Push/wiki"
code = "https://github.com/Z-Hub/Z-Push"

[integration]
yunohost = ">= 11.2.20"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

[resources]
        [resources.sources.main]
        url = "https://github.com/Z-Hub/Z-Push/archive/refs/tags/2.7.5.tar.gz"
        sha256 = "8b0009c531898f7753a6e02de2df4156b06d973cd51872787994b7d571aa0e65"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"

    [resources.apt]
    packages = [
        "php8.3-soap",
        "php8.3-imap",
        "php8.3-xsl",
        "php8.3-curl",
        "php8.3-xml",
        "php8.3-ldap",
        "php8.3-cli",
        "php8.3-mbstring",
        "php8.3-memcached",
        "libawl-php",
    ]
