#!/bin/bash

app=$YNH_APP_INSTANCE_NAME
domain=$(sudo yunohost app setting $app domain)

# Cleaning
sudo rm -rf /var/www/$app
sudo rm -rf /var/log/$app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# Restart of services
sudo service php5-fpm reload
sudo service nginx reload
sudo yunohost app ssowatconf
