#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	#### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
statedir=$(ynh_app_setting_get $app statedir)
final_logpath=$(ynh_app_setting_get $app final_logpath)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_webpath_available $domain $path_url \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d $final_path \
	|| ynh_die "There is already a directory: $final_path "

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_restore_file "$final_path"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================

#db_pwd=$(ynh_app_setting_get $app mysqlpwd)
#ynh_mysql_setup_db $db_name $db_name $db_pwd
#ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql

#=================================================
# RECREATE THE DEDICATED USER
#=================================================

# Create the dedicated user (if not existing)
#ynh_system_user_create $app

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chown -R www-data: $final_path

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================

ynh_restore_file "/etc/php5/fpm/pool.d/$app.conf"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================

# Define and install dependencies
ynh_install_app_dependencies php-soap php5-imap libawl-php php5-xsl

# Restore statedir
sudo mkdir -p $statedir
sudo cp -a ./statedir/. $statedir/
sudo chown -R www-data:www-data $statedir

# Restore logs, data & permissions
sudo mkdir -p $final_logpath
sudo cp -a ./logs/. $final_logpath/
sudo chown -R www-data:www-data $final_logpath


#=================================================
# RESTORE SYSTEMD
#=================================================

#ynh_restore_file "/etc/systemd/system/$app.service"
#systemctl enable $app.service

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

#yunohost service add $app --log "/var/log/$app/APP.log"

#=================================================
# RESTORE THE CRON FILE
#=================================================

#ynh_restore_file "/etc/cron.d/$app"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================

ynh_restore_file "/etc/logrotate.d/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================

systemctl reload php5-fpm
systemctl reload nginx
